#!/usr/bin/env python3
# Handling: Unclassified — public
# SPDX-License-Identifier: Apache-2.0
"""Export schema/openchokepoint.yaml as JSON Schema (draft 2020-12).

Usage:
    python3 tools/export_jsonschema.py            # write schema/openchokepoint.schema.json
    python3 tools/export_jsonschema.py --check    # exit 1 if the committed file is out of date

The YAML schema stays the single source of truth; the JSON file is generated from it so that
tools in any language can check record STRUCTURE. Cross-record rules (EV-, CI- and DT- rule IDs:
pointer-only evidence, synthetic-only judgments, step order) need the whole graph and are enforced
only by tools/validate.py. A file that passes the JSON Schema has not passed validation.
"""
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "schema" / "openchokepoint.yaml"
OUT = ROOT / "schema" / "openchokepoint.schema.json"

# Mirrors the value checks in tools/validate.py.
ISO3166 = r"^[A-Z]{2}(-[A-Z0-9]{1,3})?$"
URL = r"^https?://\S+$"


def value_schema(spec):
    t = spec["type"]
    base = {
        "string": {"type": "string", "minLength": 1, "pattern": r"\S"},
        "integer": {"type": "integer"},
        "decimal": {"type": "number"},
        "boolean": {"type": "boolean"},
        "date": {"type": "string", "format": "date"},
        "iso3166": {"type": "string", "pattern": ISO3166},
        "url": {"type": "string", "pattern": URL},
        "enum": {"enum": list(spec.get("values", []))},
        "ref": {"type": "string", "minLength": 1},
    }[t]
    if spec.get("many"):
        return {"type": "array", "minItems": 1, "items": base}
    return dict(base)


def record_schema(type_name, own_props, shared, extra_required=()):
    props = {**shared, **(own_props or {})}
    properties = {"type": {"const": type_name}}
    required = ["type"]
    for name, spec in props.items():
        properties[name] = value_schema(spec)
        if spec.get("required"):
            required.append(name)
    for name in extra_required:
        properties[name] = {"type": "string", "minLength": 1}
        required.append(name)
    return {"type": "object", "properties": properties, "required": required, "additionalProperties": False}


def build(onto):
    shared = onto["shared_properties"]
    defs = {}
    for name, spec in onto["object_types"].items():
        d = record_schema(name, spec.get("properties"), shared)
        if spec.get("description"):
            d["description"] = " ".join(str(spec["description"]).split())
        defs[name] = d
    for name, spec in onto["link_types"].items():
        d = record_schema(name, spec.get("properties"), shared, extra_required=("from", "to"))
        d["description"] = f"Link from {', '.join(spec['from'])} to {', '.join(spec['to'])}."
        defs[f"link.{name}"] = d
    meta = onto["schema"]
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": (
            "Handling: Unclassified — public. GENERATED by tools/export_jsonschema.py from "
            "schema/openchokepoint.yaml; do not edit by hand. Structure only: cross-record rules "
            "(EV-, CI-, DT-) are enforced by tools/validate.py. Apache-2.0."
        ),
        "title": f"OpenChokepoint instance file (schema {meta['version']})",
        "type": "object",
        "properties": {
            "objects": {"type": "array", "items": {"oneOf": [{"$ref": f"#/$defs/{n}"} for n in onto["object_types"]]}},
            "links": {"type": "array", "items": {"oneOf": [{"$ref": f"#/$defs/link.{n}"} for n in onto["link_types"]]}},
        },
        "additionalProperties": False,
        "$defs": defs,
    }


def render():
    with open(SRC, encoding="utf-8") as fh:
        onto = yaml.safe_load(fh)
    return json.dumps(build(onto), indent=2, ensure_ascii=False) + "\n"


def main(argv):
    text = render()
    if "--check" in argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is out of date; run: python3 tools/export_jsonschema.py")
            return 1
        print(f"OK   {OUT.relative_to(ROOT)} matches schema/openchokepoint.yaml")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
